/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#ffede6",
        "background": "#faf8ff",
        "tertiary-fixed": "#ffdbcd",
        "on-tertiary-fixed": "#360f00",
        "tertiary": "#943700",
        "tertiary-fixed-dim": "#ffb596",
        "surface-container-highest": "#e1e2ed",
        "primary-fixed": "#dbe1ff",
        "on-surface": "#191b23",
        "primary-container": "#2563eb",
        "tertiary-container": "#bc4800",
        "secondary-fixed-dim": "#b7c8e1",
        "surface-variant": "#e1e2ed",
        "surface-container-high": "#e7e7f3",
        "primary-fixed-dim": "#b4c5ff",
        "surface-container": "#ededf9",
        "on-primary": "#ffffff",
        "on-background": "#191b23",
        "secondary": "#505f76",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#003ea8",
        "secondary-fixed": "#d3e4fe",
        "on-primary-container": "#eeefff",
        "inverse-primary": "#b4c5ff",
        "on-secondary-container": "#54647a",
        "primary": "#004ac6",
        "on-tertiary-fixed-variant": "#7d2d00",
        "on-surface-variant": "#434655",
        "on-error-container": "#93000a",
        "outline-variant": "#c3c6d7",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#38485d",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2e3039",
        "surface-container-low": "#f3f3fe",
        "outline": "#737686",
        "error": "#ba1a1a",
        "inverse-on-surface": "#f0f0fb",
        "secondary-container": "#d0e1fb",
        "surface-dim": "#d9d9e5",
        "on-secondary-fixed": "#0b1c30",
        "surface": "#faf8ff",
        "on-tertiary": "#ffffff",
        "surface-tint": "#0053db",
        "on-primary-fixed": "#00174b",
        "surface-bright": "#faf8ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "enterprise": "16px"
      },
      spacing: {
        "gutter": "24px",
        "stack-gap": "16px",
        "sidebar-width": "280px",
        "container-max": "1440px",
        "sidebar-collapsed": "80px",
        "margin-desktop": "32px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "sidebar-item": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
        "display": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "sidebar-item": ["14px", { "lineHeight": "20px", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "500" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
